### ISSUE TITLE
Show padlock icon next to filename in left sidebar for overview of which files are encrypted

### ISSUE THREAD

**Issue by luhanbing** [tejado/obsidian-gpgCrypt#2]
For a much better user experience, it would be helpful to show a padlock icon in the file browser next to encrypted files to quickly see an overview of which files in the vault are encrypted.

Otherwise, you have to manually click on every single file in your vault and look for a padlock in the bottom right corner each time to learn which files are encrypted?

(If it's not possible for an Obsidian plugin to add an icon in the file browser in the left sidebar, then creating a separate left sidebar panel listing all encrypted files could be an alternative solution.)

**Comment by tejado** [comment]
Hi @luhanbing 
Thanks for your comment.
Currently Obisidan doesn't know if a file is encrypted until the first read of the file which happens when the note is opened.

To make it more clear and still efficient (so not reading hundreds of files at Obsidian start), I could implement an optional mode that notes will be renamed to .gpg extension. Then the file type is clearly visible and can be shown in the file browser.
What do you think about this solution?

**Comment by luhanbing** [comment]
@tejado thanks for the amazing plugin!

Yes, I think the best options are either:

- to create a new file in the vault for the plugin to store an index of all the encrypted files (add filename to the index when it is encrypted) and then use the index to display padlock in file browser
- or, as you suggested, to rename the files with .gpg extension, which might also help prevent Obsidian indexing the encrypted file contents and trying to search encrypted files?

**Comment by tejado** [comment]
Implemented in release https://github.com/tejado/obsidian-gpgCrypt/releases/tag/0.2.0
I would be delighted if you could give me some feedback on this.

**Comment by tejado** [comment]
Unfortunately, notes with gpg file extensions have some limitations, e.g. embedding a note with gpg file extension doesn't work.
